# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('creator_id', models.IntegerField(verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe8\x80\x85')),
                ('last_editor_id', models.IntegerField(verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe8\x80\x85')),
                ('ip', models.CharField(max_length=100, verbose_name='\u670d\u52a1\u5668IP')),
                ('port', models.CharField(max_length=10, verbose_name='\u7aef\u53e3\u53f7')),
                ('server_name', models.CharField(max_length=200, verbose_name='\u670d\u52a1\u540d')),
            ],
            options={
                'db_table': 'linux_sheller_app_ipmodel',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ipmodel',
            unique_together=set([('ip',)]),
        ),
        migrations.AlterIndexTogether(
            name='ipmodel',
            index_together=set([('created_time',), ('server_name',)]),
        ),
    ]
