# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linux_sheller_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipmodel',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='ipmodel',
            name='last_editor_id',
        ),
    ]
